# Generated by Django 4.2.16 on 2024-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='consecutivo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
